tinyMCE.addI18n('zh.media_dlg',{
title:"插入 / 编辑 嵌入的文档",
general:"通用",
advanced:"高级",
file:"文件/URL",
list:"列表",
size:"尺寸",
preview:"预览",
constrain_proportions:"Constrain proportions",
type:"类型",
id:"Id",
name:"名称",
class_name:"类",
vspace:"垂直间距",
hspace:"水平间距",
play:"自动播放",
loop:"循环",
menu:"显示菜单",
quality:"品质",
scale:"缩放",
align:"对其",
salign:"SAlign",
wmode:"WMode",
bgcolor:"背景色",
base:"Base",
flashvars:"Flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"缓存",
hidden:"隐藏",
controller:"控制器",
kioskmode:"Kiosk 模式",
playeveryframe:"播放每一帧",
targetcache:"目标缓存",
correction:"不正确",
enablejavascript:"启用javascript",
starttime:"开始时间",
endtime:"结束时间",
href:"Href",
qtsrcchokespeed:"Choke speed",
target:"Target",
volume:"声音",
autostart:"自动开始",
enabled:"已启用",
fullscreen:"全屏",
invokeurls:"Invoke URLs",
mute:"Mute",
stretchtofit:"Stretch to fit",
windowlessvideo:"Windowless video",
balance:"Balance",
baseurl:"Base URL",
captioningid:"Captioning id",
currentmarker:"Current marker",
currentposition:"Current position",
defaultframe:"Default frame",
playcount:"Play count",
rate:"Rate",
uimode:"UI Mode",
flash_options:"Flash options",
qt_options:"Quicktime options",
wmp_options:"Windows media player options",
rmp_options:"Real media player options",
shockwave_options:"Shockwave options",
autogotourl:"Auto goto URL",
center:"Center",
imagestatus:"Image status",
maintainaspect:"Maintain aspect",
nojava:"No java",
prefetch:"Prefetch",
shuffle:"Shuffle",
console:"Console",
numloop:"Num loops",
controls:"Controls",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Stretch style",
swstretchhalign:"Stretch H-Align",
swstretchvalign:"Stretch V-Align",
sound:"Sound",
progress:"Progress",
qtsrc:"QT Src",
qt_stream_warn:"Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..",
align_top:"上",
align_right:"右",
align_bottom:"下",
align_left:"左",
align_center:"中",
align_top_left:"左上",
align_top_right:"右上",
align_bottom_left:"左下",
align_bottom_right:"右下",
flv_options:"Flash视屏选项",
flv_scalemode:"缩放模式",
flv_buffer:"缓冲",
flv_starttime:"开始时间",
flv_defaultvolume:"默认音量",
flv_hiddengui:"隐藏图形界面",
flv_autostart:"自动开始",
flv_loop:"循环",
flv_showscalemodes:"显示缩放模式",
flv_smoothvideo:"平滑视屏",
flv_jscallback:"JS回调",
html5_video_options:"HTML5视屏选项",
altsource1:"备用源 1",
altsource2:"备用源 2",
preload:"预加载",
poster:"Poster",

source:"源"
});
