<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'searching' => 'Search',
	'achievement' => 'Achievement',
	'comments' => 'Comments',
	'demo' => 'Demo'
	);

$aliases = array(

	);

$disable_controller = array(

	);



/* Auto generated by Modules Administration on : 2014.12.30 21:16:05 */
