<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'achieve' => 'Achieve',
    'article' => 'Article',
    'online_message' => 'Comment',
    404 => 'Error',
    'page_home' => 'Home',
    'page' => 'Page',
    'searching' => 'Searching',
  ),
  'article' => 
  array (
    'articles/ajaxform' => 'Ajax Form',
  ),
);


/* Auto generated by Themes Administration on : 2014.12.31 01:28:46 */
